name: Renew YouTube Webhook

on:
  schedule:
    # Runs at 00:00 every 3 days
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Allows you to run it manually if needed

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Webhook Renewal Script
        run: node scripts/subscribe_webhook.js
